import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google'; // Example font import
// import styles from '@/styles/Home.module.css'; // Example CSS module import

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Mountain Care HR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}> {/* Example usage of font */}
        {/* Default Next.js welcome content or replace with your own */}
        <h1>Welcome to Mountain Care HR</h1>
      </main>
    </>
  );
}